# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-pygmsh:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    container: ghcr.io/jorgensd/jorgensd.github.io:main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # Runs a single command using the runners shell
      - name: Run python scripts
        run: |
          python3 src/pygmsh_tutorial.py

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

  test-gmsh:
    runs-on: ubuntu-24.04
    container: ghcr.io/fenics/dolfinx/dolfinx:stable
    steps:
      - uses: actions/checkout@v5
      - name: Run python scripts
        run: python3 src/tutorial_gmsh.py
